"""update table

Revision ID: d02e8699f547
Revises: dc7ce3828281
Create Date: 2023-12-18 18:41:18.723514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd02e8699f547'
down_revision: Union[str, None] = 'dc7ce3828281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('md5_results', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='md5status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('md5_results', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='md5status'),
               nullable=True)
    # ### end Alembic commands ###
