"""initiate

Revision ID: dc7ce3828281
Revises: 
Create Date: 2023-12-18 18:31:27.517266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7ce3828281'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md5_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promise_id', sa.String(), nullable=True),
    sa.Column('md5_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='md5status'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promise_id')
    )
    op.create_index(op.f('ix_md5_results_id'), 'md5_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_md5_results_id'), table_name='md5_results')
    op.drop_table('md5_results')
    # ### end Alembic commands ###
